name: 'Merge ESLint Reports'
description: 'Merges multiple ESLint report files into a single JSON file.'
author: 'Ralph Schuler'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  input_directory:
    description: The directory containing the ESLint report files
    required: true
  output_file:
    description: The file to write the merged report to
    required: false
    default: ./eslint_report.json

# Define your outputs here.
outputs:
  output_file:
    description: The file to write the merged report to

runs:
  using: node20
  main: dist/index.js
